"""Static reference data: Indian states and cities, used for address forms."""

INDIAN_STATES_CITIES = {
    "Andhra Pradesh": [
        "Visakhapatnam",
        "Vijayawada",
        "Guntur",
        "Nellore",
        "Kurnool",
        "Rajahmundry",
        "Tirupati",
        "Kadapa",
        "Anantapur",
        "Eluru",
    ],
    "Arunachal Pradesh": [
        "Itanagar",
        "Naharlagun",
        "Pasighat",
        "Tezpur",
        "Bomdila",
        "Ziro",
        "Along",
        "Tezu",
        "Changlang",
        "Khonsa",
    ],
    "Assam": [
        "Guwahati",
        "Silchar",
        "Dibrugarh",
        "Jorhat",
        "Nagaon",
        "Tinsukia",
        "Tezpur",
        "Bongaigaon",
        "Karimganj",
        "Sivasagar",
    ],
    "Bihar": [
        "Patna",
        "Gaya",
        "Bhagalpur",
        "Muzaffarpur",
        "Purnia",
        "Darbhanga",
        "Bihar Sharif",
        "Arrah",
        "Begusarai",
        "Katihar",
    ],
    "Chhattisgarh": [
        "Raipur",
        "Bhilai",
        "Korba",
        "Bilaspur",
        "Durg",
        "Rajnandgaon",
        "Jagdalpur",
        "Raigarh",
        "Ambikapur",
        "Mahasamund",
    ],
    "Goa": [
        "Panaji",
        "Vasco da Gama",
        "Margao",
        "Mapusa",
        "Ponda",
        "Bicholim",
        "Curchorem",
        "Sanquelim",
        "Valpoi",
        "Pernem",
    ],
    "Gujarat": [
        "Ahmedabad",
        "Surat",
        "Vadodara",
        "Rajkot",
        "Bhavnagar",
        "Jamnagar",
        "Junagadh",
        "Gandhinagar",
        "Anand",
        "Navsari",
    ],
    "Haryana": [
        "Faridabad",
        "Gurgaon",
        "Panipat",
        "Ambala",
        "Yamunanagar",
        "Rohtak",
        "Hisar",
        "Karnal",
        "Sonipat",
        "Panchkula",
    ],
    "Himachal Pradesh": [
        "Shimla",
        "Dharamshala",
        "Solan",
        "Mandi",
        "Palampur",
        "Baddi",
        "Nahan",
        "Paonta Sahib",
        "Sundernagar",
        "Chamba",
    ],
    "Jharkhand": [
        "Ranchi",
        "Jamshedpur",
        "Dhanbad",
        "Bokaro",
        "Deoghar",
        "Phusro",
        "Hazaribagh",
        "Giridih",
        "Ramgarh",
        "Medininagar",
    ],
    "Karnataka": [
        "Bangalore",
        "Mysore",
        "Hubli",
        "Mangalore",
        "Belgaum",
        "Gulbarga",
        "Davanagere",
        "Bellary",
        "Bijapur",
        "Shimoga",
    ],
    "Kerala": [
        "Thiruvananthapuram",
        "Kochi",
        "Kozhikode",
        "Thrissur",
        "Kollam",
        "Palakkad",
        "Alappuzha",
        "Malappuram",
        "Kannur",
        "Kasaragod",
    ],
    "Madhya Pradesh": [
        "Bhopal",
        "Indore",
        "Gwalior",
        "Jabalpur",
        "Ujjain",
        "Sagar",
        "Dewas",
        "Satna",
        "Ratlam",
        "Rewa",
    ],
    "Maharashtra": [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Thane",
        "Nashik",
        "Aurangabad",
        "Solapur",
        "Amravati",
        "Kolhapur",
        "Sangli",
    ],
    "Manipur": [
        "Imphal",
        "Thoubal",
        "Bishnupur",
        "Churachandpur",
        "Kakching",
        "Ukhrul",
        "Senapati",
        "Tamenglong",
        "Jiribam",
        "Moreh",
    ],
    "Meghalaya": [
        "Shillong",
        "Tura",
        "Cherrapunji",
        "Jowai",
        "Baghmara",
        "Nongpoh",
        "Mawkyrwat",
        "Resubelpara",
        "Ampati",
        "Williamnagar",
    ],
    "Mizoram": [
        "Aizawl",
        "Lunglei",
        "Saiha",
        "Champhai",
        "Kolasib",
        "Serchhip",
        "Mamit",
        "Lawngtlai",
        "Saitual",
        "Khawzawl",
    ],
    "Nagaland": [
        "Kohima",
        "Dimapur",
        "Mokokchung",
        "Tuensang",
        "Wokha",
        "Zunheboto",
        "Phek",
        "Kiphire",
        "Longleng",
        "Peren",
    ],
    "Odisha": [
        "Bhubaneswar",
        "Cuttack",
        "Rourkela",
        "Berhampur",
        "Sambalpur",
        "Puri",
        "Balasore",
        "Bhadrak",
        "Baripada",
        "Jharsuguda",
    ],
    "Punjab": [
        "Ludhiana",
        "Amritsar",
        "Jalandhar",
        "Patiala",
        "Bathinda",
        "Mohali",
        "Firozpur",
        "Batala",
        "Pathankot",
        "Moga",
    ],
    "Rajasthan": [
        "Jaipur",
        "Jodhpur",
        "Kota",
        "Bikaner",
        "Ajmer",
        "Udaipur",
        "Bhilwara",
        "Alwar",
        "Bharatpur",
        "Sikar",
    ],
    "Sikkim": [
        "Gangtok",
        "Namchi",
        "Geyzing",
        "Mangan",
        "Jorethang",
        "Nayabazar",
        "Rangpo",
        "Singtam",
        "Pakyong",
        "Ravangla",
    ],
    "Tamil Nadu": [
        "Chennai",
        "Coimbatore",
        "Madurai",
        "Tiruchirappalli",
        "Salem",
        "Tirunelveli",
        "Tiruppur",
        "Vellore",
        "Erode",
        "Thoothukkudi",
    ],
    "Telangana": [
        "Hyderabad",
        "Warangal",
        "Nizamabad",
        "Khammam",
        "Karimnagar",
        "Ramagundam",
        "Mahbubnagar",
        "Nalgonda",
        "Adilabad",
        "Suryapet",
    ],
    "Tripura": [
        "Agartala",
        "Dharmanagar",
        "Udaipur",
        "Kailasahar",
        "Belonia",
        "Khowai",
        "Ambassa",
        "Ranir Bazar",
        "Sonamura",
        "Kumarghat",
    ],
    "Uttar Pradesh": [
        "Lucknow",
        "Kanpur",
        "Ghaziabad",
        "Agra",
        "Varanasi",
        "Meerut",
        "Allahabad",
        "Bareilly",
        "Aligarh",
        "Moradabad",
    ],
    "Uttarakhand": [
        "Dehradun",
        "Haridwar",
        "Roorkee",
        "Haldwani",
        "Rudrapur",
        "Kashipur",
        "Rishikesh",
        "Kotdwar",
        "Pithoragarh",
        "Almora",
    ],
    "West Bengal": [
        "Kolkata",
        "Howrah",
        "Durgapur",
        "Asansol",
        "Siliguri",
        "Bardhaman",
        "Malda",
        "Baharampur",
        "Habra",
        "Kharagpur",
    ],
    "Andaman and Nicobar Islands": [
        "Port Blair",
        "Bamboo Flat",
        "Garacharma",
        "Diglipur",
        "Mayabunder",
        "Rangat",
        "Campbell Bay",
        "Car Nicobar",
        "Hut Bay",
        "Neil Island",
    ],
    "Chandigarh": ["Chandigarh"],
    "Dadra and Nagar Haveli and Daman and Diu": [
        "Daman",
        "Diu",
        "Silvassa",
        "Dadra",
        "Nagar Haveli",
    ],
    "Delhi": [
        "New Delhi",
        "North Delhi",
        "South Delhi",
        "East Delhi",
        "West Delhi",
        "Central Delhi",
        "North East Delhi",
        "North West Delhi",
        "South East Delhi",
        "South West Delhi",
    ],
    "Jammu and Kashmir": [
        "Srinagar",
        "Jammu",
        "Baramulla",
        "Anantnag",
        "Kupwara",
        "Pulwama",
        "Rajouri",
        "Kathua",
        "Udhampur",
        "Reasi",
    ],
    "Ladakh": [
        "Leh",
        "Kargil",
        "Nubra",
        "Zanskar",
        "Changthang",
        "Sham",
        "Rupshu",
        "Dras",
        "Sankoo",
        "Turtuk",
    ],
    "Lakshadweep": [
        "Kavaratti",
        "Agatti",
        "Minicoy",
        "Amini",
        "Andrott",
        "Kalpeni",
        "Kadmat",
        "Kiltan",
        "Chetlat",
        "Bitra",
    ],
    "Puducherry": [
        "Puducherry",
        "Karaikal",
        "Mahe",
        "Yanam",
        "Oulgaret",
        "Villianur",
        "Ariyankuppam",
        "Mannadipet",
        "Bahour",
        "Nettapakkam",
    ],
}


def get_indian_states():
    """Get list of Indian states"""
    return list(INDIAN_STATES_CITIES.keys())


def get_cities_by_state(state):
    """Get cities for a specific state"""
    return INDIAN_STATES_CITIES.get(state, [])


# ----------------------------
# Email Setup
